//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.epacdxnode.test
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NodeFaultDetailType
    {
        
        private ErrorCodeList errorCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCodeList errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum ErrorCodeList
    {
        
        /// <remarks/>
        E_UnknownUser,
        
        /// <remarks/>
        E_InvalidCredential,
        
        /// <remarks/>
        E_TransactionId,
        
        /// <remarks/>
        E_UnknownMethod,
        
        /// <remarks/>
        E_ServiceUnavailable,
        
        /// <remarks/>
        E_AccessDenied,
        
        /// <remarks/>
        E_InvalidToken,
        
        /// <remarks/>
        E_FileNotFound,
        
        /// <remarks/>
        E_TokenExpired,
        
        /// <remarks/>
        E_ValidationFailed,
        
        /// <remarks/>
        E_ServerBusy,
        
        /// <remarks/>
        E_RowIdOutofRange,
        
        /// <remarks/>
        E_FeatureUnsupported,
        
        /// <remarks/>
        E_VersionMismatch,
        
        /// <remarks/>
        E_InvalidFileName,
        
        /// <remarks/>
        E_InvalidFileType,
        
        /// <remarks/>
        E_InvalidDataflow,
        
        /// <remarks/>
        E_InvalidParameter,
        
        /// <remarks/>
        E_AuthMethod,
        
        /// <remarks/>
        E_Unknown,
        
        /// <remarks/>
        E_QueryReturnSetTooBig,
        
        /// <remarks/>
        E_DBMSError,
        
        /// <remarks/>
        E_RecipientNotSupported,
        
        /// <remarks/>
        E_NotificationURINotSupported,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.exchangenetwork.net/wsdl/node/2", ConfigurationName="net.epacdxnode.test.NetworkNodePortType2")]
    public interface NetworkNodePortType2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.AuthenticateResponse1> AuthenticateAsync(net.epacdxnode.test.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.SubmitResponse> SubmitAsync(net.epacdxnode.test.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.GetStatusResponse> GetStatusAsync(net.epacdxnode.test.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.NotifyResponse> NotifyAsync(net.epacdxnode.test.NotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.DownloadResponse> DownloadAsync(net.epacdxnode.test.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.QueryResponse> QueryAsync(net.epacdxnode.test.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.SolicitResponse> SolicitAsync(net.epacdxnode.test.SolicitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.ExecuteResponse1> ExecuteAsync(net.epacdxnode.test.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.NodePingResponse1> NodePingAsync(net.epacdxnode.test.NodePingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(net.epacdxnode.test.NodeFaultDetailType), Action="", Name="NodeFaultDetailType", Namespace="http://www.exchangenetwork.net/schema/node/2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<net.epacdxnode.test.GetServicesResponse> GetServicesAsync(net.epacdxnode.test.GetServicesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Authenticate
    {
        
        private string userIdField;
        
        private string credentialField;
        
        private string domainField;
        
        private string authenticationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string authenticationMethod
        {
            get
            {
                return this.authenticationMethodField;
            }
            set
            {
                this.authenticationMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class AuthenticateResponse
    {
        
        private string securityTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Authenticate Authenticate;
        
        public AuthenticateRequest()
        {
        }
        
        public AuthenticateRequest(net.epacdxnode.test.Authenticate Authenticate)
        {
            this.Authenticate = Authenticate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.AuthenticateResponse AuthenticateResponse;
        
        public AuthenticateResponse1()
        {
        }
        
        public AuthenticateResponse1(net.epacdxnode.test.AuthenticateResponse AuthenticateResponse)
        {
            this.AuthenticateResponse = AuthenticateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Submit
    {
        
        private string securityTokenField;
        
        private string transactionIdField;
        
        private string dataflowField;
        
        private string flowOperationField;
        
        private string[] recipientField;
        
        private NotificationURIType[] notificationURIField;
        
        private NodeDocumentType[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=2)]
        public string dataflow
        {
            get
            {
                return this.dataflowField;
            }
            set
            {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string flowOperation
        {
            get
            {
                return this.flowOperationField;
            }
            set
            {
                this.flowOperationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipient", Order=4)]
        public string[] recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notificationURI", Order=5)]
        public NotificationURIType[] notificationURI
        {
            get
            {
                return this.notificationURIField;
            }
            set
            {
                this.notificationURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documents", Order=6)]
        public NodeDocumentType[] documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NotificationURIType
    {
        
        private NotificationTypeCode notificationTypeField;
        
        private bool notificationTypeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NotificationTypeCode notificationType
        {
            get
            {
                return this.notificationTypeField;
            }
            set
            {
                this.notificationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notificationTypeSpecified
        {
            get
            {
                return this.notificationTypeFieldSpecified;
            }
            set
            {
                this.notificationTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum NotificationTypeCode
    {
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NodeDocumentType
    {
        
        private string documentNameField;
        
        private DocumentFormatType documentFormatField;
        
        private AttachmentType documentContentField;
        
        private string documentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DocumentFormatType documentFormat
        {
            get
            {
                return this.documentFormatField;
            }
            set
            {
                this.documentFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AttachmentType documentContent
        {
            get
            {
                return this.documentContentField;
            }
            set
            {
                this.documentContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string documentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum DocumentFormatType
    {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        FLAT,
        
        /// <remarks/>
        BIN,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        ODF,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class AttachmentType
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/2005/05/xmlmime")]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class StatusResponseType
    {
        
        private string transactionIdField;
        
        private TransactionStatusCode statusField;
        
        private string statusDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TransactionStatusCode status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string statusDetail
        {
            get
            {
                return this.statusDetailField;
            }
            set
            {
                this.statusDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum TransactionStatusCode
    {
        
        /// <remarks/>
        Received,
        
        /// <remarks/>
        Processing,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Processed,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Unknown,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Submit Submit;
        
        public SubmitRequest()
        {
        }
        
        public SubmitRequest(net.epacdxnode.test.Submit Submit)
        {
            this.Submit = Submit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.StatusResponseType SubmitResponse1;
        
        public SubmitResponse()
        {
        }
        
        public SubmitResponse(net.epacdxnode.test.StatusResponseType SubmitResponse1)
        {
            this.SubmitResponse1 = SubmitResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class GetStatus
    {
        
        private string securityTokenField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.GetStatus GetStatus;
        
        public GetStatusRequest()
        {
        }
        
        public GetStatusRequest(net.epacdxnode.test.GetStatus GetStatus)
        {
            this.GetStatus = GetStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.StatusResponseType GetStatusResponse1;
        
        public GetStatusResponse()
        {
        }
        
        public GetStatusResponse(net.epacdxnode.test.StatusResponseType GetStatusResponse1)
        {
            this.GetStatusResponse1 = GetStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Notify
    {
        
        private string securityTokenField;
        
        private string nodeAddressField;
        
        private string dataflowField;
        
        private NotificationMessageType[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nodeAddress
        {
            get
            {
                return this.nodeAddressField;
            }
            set
            {
                this.nodeAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=2)]
        public string dataflow
        {
            get
            {
                return this.dataflowField;
            }
            set
            {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Order=3)]
        public NotificationMessageType[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NotificationMessageType
    {
        
        private NotificationMessageCategoryType messageCategoryField;
        
        private string messageNameField;
        
        private TransactionStatusCode statusField;
        
        private string statusDetailField;
        
        private string objectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationMessageCategoryType messageCategory
        {
            get
            {
                return this.messageCategoryField;
            }
            set
            {
                this.messageCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string messageName
        {
            get
            {
                return this.messageNameField;
            }
            set
            {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionStatusCode status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string statusDetail
        {
            get
            {
                return this.statusDetailField;
            }
            set
            {
                this.statusDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum NotificationMessageCategoryType
    {
        
        /// <remarks/>
        Event,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Document,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Notify Notify;
        
        public NotifyRequest()
        {
        }
        
        public NotifyRequest(net.epacdxnode.test.Notify Notify)
        {
            this.Notify = Notify;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.StatusResponseType NotifyResponse1;
        
        public NotifyResponse()
        {
        }
        
        public NotifyResponse(net.epacdxnode.test.StatusResponseType NotifyResponse1)
        {
            this.NotifyResponse1 = NotifyResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Download
    {
        
        private string securityTokenField;
        
        private string dataflowField;
        
        private string transactionIdField;
        
        private NodeDocumentType[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=1)]
        public string dataflow
        {
            get
            {
                return this.dataflowField;
            }
            set
            {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documents", Order=3)]
        public NodeDocumentType[] documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Download Download;
        
        public DownloadRequest()
        {
        }
        
        public DownloadRequest(net.epacdxnode.test.Download Download)
        {
            this.Download = Download;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("documents", IsNullable=false)]
        public net.epacdxnode.test.NodeDocumentType[] DownloadResponse1;
        
        public DownloadResponse()
        {
        }
        
        public DownloadResponse(net.epacdxnode.test.NodeDocumentType[] DownloadResponse1)
        {
            this.DownloadResponse1 = DownloadResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Query
    {
        
        private string securityTokenField;
        
        private string dataflowField;
        
        private string requestField;
        
        private string rowIdField;
        
        private string maxRowsField;
        
        private ParameterType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=1)]
        public string dataflow
        {
            get
            {
                return this.dataflowField;
            }
            set
            {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string rowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string maxRows
        {
            get
            {
                return this.maxRowsField;
            }
            set
            {
                this.maxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", Order=5)]
        public ParameterType[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class ParameterType
    {
        
        private string parameterNameField;
        
        private System.Xml.XmlQualifiedName parameterTypeField;
        
        private EncodingType parameterEncodingField;
        
        private string valueField;
        
        public ParameterType()
        {
            this.parameterEncodingField = EncodingType.None;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parameterName
        {
            get
            {
                return this.parameterNameField;
            }
            set
            {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName parameterType
        {
            get
            {
                return this.parameterTypeField;
            }
            set
            {
                this.parameterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EncodingType.None)]
        public EncodingType parameterEncoding
        {
            get
            {
                return this.parameterEncodingField;
            }
            set
            {
                this.parameterEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum EncodingType
    {
        
        /// <remarks/>
        Base64,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        Encrypt,
        
        /// <remarks/>
        Digest,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class ResultSetType
    {
        
        private string rowIdField;
        
        private string rowCountField;
        
        private bool lastSetField;
        
        private GenericXmlType resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string rowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string rowCount
        {
            get
            {
                return this.rowCountField;
            }
            set
            {
                this.rowCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool lastSet
        {
            get
            {
                return this.lastSetField;
            }
            set
            {
                this.lastSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public GenericXmlType results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class GenericXmlType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private DocumentFormatType formatField;
        
        public GenericXmlType()
        {
            this.formatField = DocumentFormatType.XML;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DocumentFormatType.XML)]
        public DocumentFormatType format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Query Query;
        
        public QueryRequest()
        {
        }
        
        public QueryRequest(net.epacdxnode.test.Query Query)
        {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.ResultSetType QueryResponse1;
        
        public QueryResponse()
        {
        }
        
        public QueryResponse(net.epacdxnode.test.ResultSetType QueryResponse1)
        {
            this.QueryResponse1 = QueryResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Solicit
    {
        
        private string securityTokenField;
        
        private string dataflowField;
        
        private string requestField;
        
        private string[] recipientField;
        
        private NotificationURIType[] notificationURIField;
        
        private ParameterType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=1)]
        public string dataflow
        {
            get
            {
                return this.dataflowField;
            }
            set
            {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipient", Order=3)]
        public string[] recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notificationURI", Order=4)]
        public NotificationURIType[] notificationURI
        {
            get
            {
                return this.notificationURIField;
            }
            set
            {
                this.notificationURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", Order=5)]
        public ParameterType[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Solicit Solicit;
        
        public SolicitRequest()
        {
        }
        
        public SolicitRequest(net.epacdxnode.test.Solicit Solicit)
        {
            this.Solicit = Solicit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.StatusResponseType SolicitResponse1;
        
        public SolicitResponse()
        {
        }
        
        public SolicitResponse(net.epacdxnode.test.StatusResponseType SolicitResponse1)
        {
            this.SolicitResponse1 = SolicitResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class Execute
    {
        
        private string securityTokenField;
        
        private string interfaceNameField;
        
        private string methodNameField;
        
        private ParameterType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string interfaceName
        {
            get
            {
                return this.interfaceNameField;
            }
            set
            {
                this.interfaceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string methodName
        {
            get
            {
                return this.methodNameField;
            }
            set
            {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", Order=3)]
        public ParameterType[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class ExecuteResponse
    {
        
        private string transactionIdField;
        
        private TransactionStatusCode statusField;
        
        private GenericXmlType resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TransactionStatusCode status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GenericXmlType results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.Execute Execute;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(net.epacdxnode.test.Execute Execute)
        {
            this.Execute = Execute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.ExecuteResponse ExecuteResponse;
        
        public ExecuteResponse1()
        {
        }
        
        public ExecuteResponse1(net.epacdxnode.test.ExecuteResponse ExecuteResponse)
        {
            this.ExecuteResponse = ExecuteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NodePing
    {
        
        private string helloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hello
        {
            get
            {
                return this.helloField;
            }
            set
            {
                this.helloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class NodePingResponse
    {
        
        private NodeStatusCode nodeStatusField;
        
        private string statusDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NodeStatusCode nodeStatus
        {
            get
            {
                return this.nodeStatusField;
            }
            set
            {
                this.nodeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusDetail
        {
            get
            {
                return this.statusDetailField;
            }
            set
            {
                this.statusDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public enum NodeStatusCode
    {
        
        /// <remarks/>
        Ready,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Busy,
        
        /// <remarks/>
        Unknown,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NodePingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.NodePing NodePing;
        
        public NodePingRequest()
        {
        }
        
        public NodePingRequest(net.epacdxnode.test.NodePing NodePing)
        {
            this.NodePing = NodePing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NodePingResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.NodePingResponse NodePingResponse;
        
        public NodePingResponse1()
        {
        }
        
        public NodePingResponse1(net.epacdxnode.test.NodePingResponse NodePingResponse)
        {
            this.NodePingResponse = NodePingResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/node/2")]
    public partial class GetServices
    {
        
        private string securityTokenField;
        
        private string serviceCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string securityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceCategory
        {
            get
            {
                return this.serviceCategoryField;
            }
            set
            {
                this.serviceCategoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServicesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.GetServices GetServices;
        
        public GetServicesRequest()
        {
        }
        
        public GetServicesRequest(net.epacdxnode.test.GetServices GetServices)
        {
            this.GetServices = GetServices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServicesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServicesResponse", Namespace="http://www.exchangenetwork.net/schema/node/2", Order=0)]
        public net.epacdxnode.test.GenericXmlType GetServicesResponse1;
        
        public GetServicesResponse()
        {
        }
        
        public GetServicesResponse(net.epacdxnode.test.GenericXmlType GetServicesResponse1)
        {
            this.GetServicesResponse1 = GetServicesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NetworkNodePortType2Channel : net.epacdxnode.test.NetworkNodePortType2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NetworkNodePortType2Client : System.ServiceModel.ClientBase<net.epacdxnode.test.NetworkNodePortType2>, net.epacdxnode.test.NetworkNodePortType2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NetworkNodePortType2Client() : 
                base(NetworkNodePortType2Client.GetDefaultBinding(), NetworkNodePortType2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetworkNodePort2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NetworkNodePortType2Client(EndpointConfiguration endpointConfiguration) : 
                base(NetworkNodePortType2Client.GetBindingForEndpoint(endpointConfiguration), NetworkNodePortType2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NetworkNodePortType2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NetworkNodePortType2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NetworkNodePortType2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NetworkNodePortType2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NetworkNodePortType2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.AuthenticateResponse1> net.epacdxnode.test.NetworkNodePortType2.AuthenticateAsync(net.epacdxnode.test.AuthenticateRequest request)
        {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.AuthenticateResponse1> AuthenticateAsync(net.epacdxnode.test.Authenticate Authenticate)
        {
            net.epacdxnode.test.AuthenticateRequest inValue = new net.epacdxnode.test.AuthenticateRequest();
            inValue.Authenticate = Authenticate;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.SubmitResponse> net.epacdxnode.test.NetworkNodePortType2.SubmitAsync(net.epacdxnode.test.SubmitRequest request)
        {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.SubmitResponse> SubmitAsync(net.epacdxnode.test.Submit Submit)
        {
            net.epacdxnode.test.SubmitRequest inValue = new net.epacdxnode.test.SubmitRequest();
            inValue.Submit = Submit;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).SubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.GetStatusResponse> net.epacdxnode.test.NetworkNodePortType2.GetStatusAsync(net.epacdxnode.test.GetStatusRequest request)
        {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.GetStatusResponse> GetStatusAsync(net.epacdxnode.test.GetStatus GetStatus)
        {
            net.epacdxnode.test.GetStatusRequest inValue = new net.epacdxnode.test.GetStatusRequest();
            inValue.GetStatus = GetStatus;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.NotifyResponse> net.epacdxnode.test.NetworkNodePortType2.NotifyAsync(net.epacdxnode.test.NotifyRequest request)
        {
            return base.Channel.NotifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.NotifyResponse> NotifyAsync(net.epacdxnode.test.Notify Notify)
        {
            net.epacdxnode.test.NotifyRequest inValue = new net.epacdxnode.test.NotifyRequest();
            inValue.Notify = Notify;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).NotifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.DownloadResponse> net.epacdxnode.test.NetworkNodePortType2.DownloadAsync(net.epacdxnode.test.DownloadRequest request)
        {
            return base.Channel.DownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.DownloadResponse> DownloadAsync(net.epacdxnode.test.Download Download)
        {
            net.epacdxnode.test.DownloadRequest inValue = new net.epacdxnode.test.DownloadRequest();
            inValue.Download = Download;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).DownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.QueryResponse> net.epacdxnode.test.NetworkNodePortType2.QueryAsync(net.epacdxnode.test.QueryRequest request)
        {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.QueryResponse> QueryAsync(net.epacdxnode.test.Query Query)
        {
            net.epacdxnode.test.QueryRequest inValue = new net.epacdxnode.test.QueryRequest();
            inValue.Query = Query;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).QueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.SolicitResponse> net.epacdxnode.test.NetworkNodePortType2.SolicitAsync(net.epacdxnode.test.SolicitRequest request)
        {
            return base.Channel.SolicitAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.SolicitResponse> SolicitAsync(net.epacdxnode.test.Solicit Solicit)
        {
            net.epacdxnode.test.SolicitRequest inValue = new net.epacdxnode.test.SolicitRequest();
            inValue.Solicit = Solicit;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).SolicitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.ExecuteResponse1> net.epacdxnode.test.NetworkNodePortType2.ExecuteAsync(net.epacdxnode.test.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.ExecuteResponse1> ExecuteAsync(net.epacdxnode.test.Execute Execute)
        {
            net.epacdxnode.test.ExecuteRequest inValue = new net.epacdxnode.test.ExecuteRequest();
            inValue.Execute = Execute;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).ExecuteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.NodePingResponse1> net.epacdxnode.test.NetworkNodePortType2.NodePingAsync(net.epacdxnode.test.NodePingRequest request)
        {
            return base.Channel.NodePingAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.NodePingResponse1> NodePingAsync(net.epacdxnode.test.NodePing NodePing)
        {
            net.epacdxnode.test.NodePingRequest inValue = new net.epacdxnode.test.NodePingRequest();
            inValue.NodePing = NodePing;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).NodePingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.epacdxnode.test.GetServicesResponse> net.epacdxnode.test.NetworkNodePortType2.GetServicesAsync(net.epacdxnode.test.GetServicesRequest request)
        {
            return base.Channel.GetServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.epacdxnode.test.GetServicesResponse> GetServicesAsync(net.epacdxnode.test.GetServices GetServices)
        {
            net.epacdxnode.test.GetServicesRequest inValue = new net.epacdxnode.test.GetServicesRequest();
            inValue.GetServices = GetServices;
            return ((net.epacdxnode.test.NetworkNodePortType2)(this)).GetServicesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetworkNodePort2))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetworkNodePort2))
            {
                return new System.ServiceModel.EndpointAddress("https://testngn.epacdxnode.net/ngn-enws20/services/NetworkNode2ServiceConditional" +
                        "MTOM");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NetworkNodePortType2Client.GetBindingForEndpoint(EndpointConfiguration.NetworkNodePort2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NetworkNodePortType2Client.GetEndpointAddress(EndpointConfiguration.NetworkNodePort2);
        }
        
        public enum EndpointConfiguration
        {
            
            NetworkNodePort2,
        }
    }
}
