//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdx.epa.gov
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Name="WQX Web ServicesSoap", Namespace="http://www.epa.gov/wqx/", ConfigurationName="cdx.epa.gov.WQXWebServicesSoap")]
    public interface WQXWebServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.epa.gov/wqx/GetDomainNames", ReplyAction="*")]
        System.Threading.Tasks.Task<cdx.epa.gov.GetDomainNamesResponse> GetDomainNamesAsync(cdx.epa.gov.GetDomainNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.epa.gov/wqx/GetDomainValues", ReplyAction="*")]
        System.Threading.Tasks.Task<cdx.epa.gov.GetDomainValuesResponse> GetDomainValuesAsync(cdx.epa.gov.GetDomainValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.epa.gov/wqx/GetDomainValuesByLastChangeDate", ReplyAction="*")]
        System.Threading.Tasks.Task<cdx.epa.gov.GetDomainValuesByLastChangeDateResponse> GetDomainValuesByLastChangeDateAsync(cdx.epa.gov.GetDomainValuesByLastChangeDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainNames", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainNamesRequestBody Body;
        
        public GetDomainNamesRequest()
        {
        }
        
        public GetDomainNamesRequest(cdx.epa.gov.GetDomainNamesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDomainNamesRequestBody
    {
        
        public GetDomainNamesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainNamesResponse", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainNamesResponseBody Body;
        
        public GetDomainNamesResponse()
        {
        }
        
        public GetDomainNamesResponse(cdx.epa.gov.GetDomainNamesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.epa.gov/wqx/")]
    public partial class GetDomainNamesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDomainNamesResult;
        
        public GetDomainNamesResponseBody()
        {
        }
        
        public GetDomainNamesResponseBody(string GetDomainNamesResult)
        {
            this.GetDomainNamesResult = GetDomainNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainValuesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainValues", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainValuesRequestBody Body;
        
        public GetDomainValuesRequest()
        {
        }
        
        public GetDomainValuesRequest(cdx.epa.gov.GetDomainValuesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.epa.gov/wqx/")]
    public partial class GetDomainValuesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domainName;
        
        public GetDomainValuesRequestBody()
        {
        }
        
        public GetDomainValuesRequestBody(string domainName)
        {
            this.domainName = domainName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainValuesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainValuesResponse", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainValuesResponseBody Body;
        
        public GetDomainValuesResponse()
        {
        }
        
        public GetDomainValuesResponse(cdx.epa.gov.GetDomainValuesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.epa.gov/wqx/")]
    public partial class GetDomainValuesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetDomainValuesResult;
        
        public GetDomainValuesResponseBody()
        {
        }
        
        public GetDomainValuesResponseBody(byte[] GetDomainValuesResult)
        {
            this.GetDomainValuesResult = GetDomainValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainValuesByLastChangeDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainValuesByLastChangeDate", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainValuesByLastChangeDateRequestBody Body;
        
        public GetDomainValuesByLastChangeDateRequest()
        {
        }
        
        public GetDomainValuesByLastChangeDateRequest(cdx.epa.gov.GetDomainValuesByLastChangeDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.epa.gov/wqx/")]
    public partial class GetDomainValuesByLastChangeDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domainName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime lastChangeDate;
        
        public GetDomainValuesByLastChangeDateRequestBody()
        {
        }
        
        public GetDomainValuesByLastChangeDateRequestBody(string domainName, System.DateTime lastChangeDate)
        {
            this.domainName = domainName;
            this.lastChangeDate = lastChangeDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainValuesByLastChangeDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainValuesByLastChangeDateResponse", Namespace="http://www.epa.gov/wqx/", Order=0)]
        public cdx.epa.gov.GetDomainValuesByLastChangeDateResponseBody Body;
        
        public GetDomainValuesByLastChangeDateResponse()
        {
        }
        
        public GetDomainValuesByLastChangeDateResponse(cdx.epa.gov.GetDomainValuesByLastChangeDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.epa.gov/wqx/")]
    public partial class GetDomainValuesByLastChangeDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDomainValuesByLastChangeDateResult;
        
        public GetDomainValuesByLastChangeDateResponseBody()
        {
        }
        
        public GetDomainValuesByLastChangeDateResponseBody(string GetDomainValuesByLastChangeDateResult)
        {
            this.GetDomainValuesByLastChangeDateResult = GetDomainValuesByLastChangeDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WQXWebServicesSoapChannel : cdx.epa.gov.WQXWebServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WQXWebServicesSoapClient : System.ServiceModel.ClientBase<cdx.epa.gov.WQXWebServicesSoap>, cdx.epa.gov.WQXWebServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WQXWebServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WQXWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), WQXWebServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WQXWebServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WQXWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WQXWebServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WQXWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WQXWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<cdx.epa.gov.GetDomainNamesResponse> GetDomainNamesAsync(cdx.epa.gov.GetDomainNamesRequest request)
        {
            return base.Channel.GetDomainNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<cdx.epa.gov.GetDomainValuesResponse> GetDomainValuesAsync(cdx.epa.gov.GetDomainValuesRequest request)
        {
            return base.Channel.GetDomainValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<cdx.epa.gov.GetDomainValuesByLastChangeDateResponse> GetDomainValuesByLastChangeDateAsync(cdx.epa.gov.GetDomainValuesByLastChangeDateRequest request)
        {
            return base.Channel.GetDomainValuesByLastChangeDateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WQX_x0020_Web_x0020_ServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WQX_x0020_Web_x0020_ServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WQX_x0020_Web_x0020_ServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cdx.epa.gov/WQXWeb/services.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WQX_x0020_Web_x0020_ServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cdx.epa.gov/WQXWeb/services.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WQX_x0020_Web_x0020_ServicesSoap,
            
            WQX_x0020_Web_x0020_ServicesSoap12,
        }
    }
}
